---
name: build_document

'on':
  workflow_dispatch:
  push:
    paths-ignore:
      - 'generated/**'

permissions:
  contents: read

jobs:
  build_document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          token: ${{secrets.PUSH_TOKEN}}
      - name: Install dependencies
        run: |
          sudo apt-get install texlive-latex-extra
      - name: run build script
        working-directory: ${{github.workspace}}
        shell: bash
        run: ./publish.sh

      - name: status at ${{github.ref}}
        run: git status

      - name: commit and push result
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          git config --global user.name 'build_document_action'
          git config --global user.email 'vil02@users.noreply.github.com'
          git add "$(./get_output_folder.sh)"
          git commit -m "Automated document generation"
          git push
...
